//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата регистрации владельца сервера.
        /// </summary>
        internal static string EditOwnerDto_DataRegistration {
            get {
                return ResourceManager.GetString("EditOwnerDto_DataRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор владельца сервера.
        /// </summary>
        internal static string EditOwnerDto_IsnNode {
            get {
                return ResourceManager.GetString("EditOwnerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя владельца сервера.
        /// </summary>
        internal static string EditOwnerDto_NameOwn {
            get {
                return ResourceManager.GetString("EditOwnerDto_NameOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игры сервера.
        /// </summary>
        internal static string EditServerDto_Games {
            get {
                return ResourceManager.GetString("EditServerDto_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор сервера.
        /// </summary>
        internal static string EditServerDto_IsnNode {
            get {
                return ResourceManager.GetString("EditServerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор владельца сервера.
        /// </summary>
        internal static string EditServerDto_IsnOwner {
            get {
                return ResourceManager.GetString("EditServerDto_IsnOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название сервера.
        /// </summary>
        internal static string EditServerDto_NameServer {
            get {
                return ResourceManager.GetString("EditServerDto_NameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характеристики сервера.
        /// </summary>
        internal static string EditServerDto_Сharacteristic {
            get {
                return ResourceManager.GetString("EditServerDto_Сharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на индефикатор пользователя.
        /// </summary>
        internal static string EditUserDto_IsnNode {
            get {
                return ResourceManager.GetString("EditUserDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на имя пользователя.
        /// </summary>
        internal static string EditUserDto_NameUser {
            get {
                return ResourceManager.GetString("EditUserDto_NameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тариф пользователя.
        /// </summary>
        internal static string EditUserDto_Tariff {
            get {
                return ResourceManager.GetString("EditUserDto_Tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата регистрации владельца сервера.
        /// </summary>
        internal static string InfoOwnerDto_DataRegistration {
            get {
                return ResourceManager.GetString("InfoOwnerDto_DataRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор владельца сервера.
        /// </summary>
        internal static string InfoOwnerDto_IsnNode {
            get {
                return ResourceManager.GetString("InfoOwnerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя владельца сервера.
        /// </summary>
        internal static string InfoOwnerDto_NameOwn {
            get {
                return ResourceManager.GetString("InfoOwnerDto_NameOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер владельца.
        /// </summary>
        internal static string InfoOwnerDto_Servers {
            get {
                return ResourceManager.GetString("InfoOwnerDto_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игры сервера.
        /// </summary>
        internal static string InfoServerDto_Games {
            get {
                return ResourceManager.GetString("InfoServerDto_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор сервера.
        /// </summary>
        internal static string InfoServerDto_IsnNode {
            get {
                return ResourceManager.GetString("InfoServerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор владельца сервера.
        /// </summary>
        internal static string InfoServerDto_IsnOwner {
            get {
                return ResourceManager.GetString("InfoServerDto_IsnOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название сервера.
        /// </summary>
        internal static string InfoServerDto_NameServer {
            get {
                return ResourceManager.GetString("InfoServerDto_NameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец Сервера.
        /// </summary>
        internal static string InfoServerDto_Owner {
            get {
                return ResourceManager.GetString("InfoServerDto_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользватели сервера.
        /// </summary>
        internal static string InfoServerDto_Users {
            get {
                return ResourceManager.GetString("InfoServerDto_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характеристики сервера.
        /// </summary>
        internal static string InfoServerDto_Сharacteristic {
            get {
                return ResourceManager.GetString("InfoServerDto_Сharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на индефикатор пользователя.
        /// </summary>
        internal static string InfoUserDto_IsnNode {
            get {
                return ResourceManager.GetString("InfoUserDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на имя пользователя.
        /// </summary>
        internal static string InfoUserDto_NameUser {
            get {
                return ResourceManager.GetString("InfoUserDto_NameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер пользователя.
        /// </summary>
        internal static string InfoUserDto_Servers {
            get {
                return ResourceManager.GetString("InfoUserDto_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тариф пользователя.
        /// </summary>
        internal static string InfoUserDto_Tariff {
            get {
                return ResourceManager.GetString("InfoUserDto_Tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата регистрации владельца сервера.
        /// </summary>
        internal static string OwnerDto_DataRegistration {
            get {
                return ResourceManager.GetString("OwnerDto_DataRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор владельца сервера.
        /// </summary>
        internal static string OwnerDto_IsnNode {
            get {
                return ResourceManager.GetString("OwnerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя владельца сервера.
        /// </summary>
        internal static string OwnerDto_NameOwn {
            get {
                return ResourceManager.GetString("OwnerDto_NameOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игры сервера.
        /// </summary>
        internal static string ServerDto_Games {
            get {
                return ResourceManager.GetString("ServerDto_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор сервера.
        /// </summary>
        internal static string ServerDto_IsnNode {
            get {
                return ResourceManager.GetString("ServerDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор владельца сервера.
        /// </summary>
        internal static string ServerDto_IsnOwner {
            get {
                return ResourceManager.GetString("ServerDto_IsnOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название сервера.
        /// </summary>
        internal static string ServerDto_NameServer {
            get {
                return ResourceManager.GetString("ServerDto_NameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характеристики сервера.
        /// </summary>
        internal static string ServerDto_Сharacteristic {
            get {
                return ResourceManager.GetString("ServerDto_Сharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индефикатор сервера.
        /// </summary>
        internal static string SetBlindWithServerDto_IsnServer {
            get {
                return ResourceManager.GetString("SetBlindWithServerDto_IsnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на индефикатор пользователя.
        /// </summary>
        internal static string SetBlindWithServerDto_IsnUser {
            get {
                return ResourceManager.GetString("SetBlindWithServerDto_IsnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на индефикатор пользователя.
        /// </summary>
        internal static string UserDto_IsnNode {
            get {
                return ResourceManager.GetString("UserDto_IsnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на имя пользователя.
        /// </summary>
        internal static string UserDto_NameUser {
            get {
                return ResourceManager.GetString("UserDto_NameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тариф пользователя.
        /// </summary>
        internal static string UserDto_Tariff {
            get {
                return ResourceManager.GetString("UserDto_Tariff", resourceCulture);
            }
        }
    }
}
